### ISSUE TITLE
Autoprefixer ^1.1.0 is failing

### ISSUE THREAD

**Issue by mr-mig** [yetu/controlcenter#13]
```
ERROR in ../~/css-loader!../~/autoprefixer-loader!../~/sass-loader?includePaths[]=/Users/mr_mig/dev/yetu/controlcenter/public/app/project-setup&includePaths[]=/Users/mr_mig/dev/yetu/controlcenter/public/bower_components/foundation/scss!./app/common/regions/navigation/nav-item/style.scss
    Module build failed: Error: "version" is a required argument.
        at Object.getArg (/Users/mr_mig/dev/yetu/controlcenter/node_modules/autoprefixer-loader/node_modules/autoprefixer-core/node_modules/postcss/node_modules/source-map/lib/source-map/util.js:28:13)
        at SourceMapConsumer.BasicSourceMapConsumer (/Users/mr_mig/dev/yetu/controlcenter/node_modules/autoprefixer-loader/node_modules/autoprefixer-core/node_modules/postcss/node_modules/source-map/lib/source-map/basic-source-map-consumer.js:54:24)
        at new SourceMapConsumer (/Users/mr_mig/dev/yetu/controlcenter/node_modules/autoprefixer-loader/node_modules/autoprefixer-core/node_modules/postcss/node_modules/source-map/lib/source-map/source-map-consumer.js:26:14)
        at PreviousMap.consumer (/Users/mr_mig/dev/yetu/controlcenter/node_modules/autoprefixer-loader/node_modules/autoprefixer-core/node_modules/postcss/lib/previous-map.js:33:34)
        at new Input (/Users/mr_mig/dev/yetu/controlcenter/node_modules/autoprefixer-loader/node_modules/autoprefixer-core/node_modules/postcss/lib/input.js:36:28)
        at Function.module.exports [as parse] (/Users/mr_mig/dev/yetu/controlcenter/node_modules/autoprefixer-loader/node_modules/autoprefixer-core/node_modules/postcss/lib/parse.js:10:17)
        at PostCSS.process (/Users/mr_mig/dev/yetu/controlcenter/node_modules/autoprefixer-loader/node_modules/autoprefixer-core/node_modules/postcss/lib/postcss.js:62:30)
        at Autoprefixer.process (/Users/mr_mig/dev/yetu/controlcenter/node_modules/autoprefixer-loader/node_modules/autoprefixer-core/lib/autoprefixer.js:57:36)
        at Object.module.exports (/Users/mr_mig/dev/yetu/controlcenter/node_modules/autoprefixer-loader/index.js:49:42)
```

**Comment by mr-mig** [comment]
Temp solution will be to use exact version `1.1.0` for autoprefixer
